<a href="https://colab.research.google.com/github/Thanaphon-673020253-2/DW_lab_6730202532/blob/main/HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Hw5

เขียน function คูณ matrix

แล้ว test กับ matrix ขนาด (2,3) * (3,2), (4,4) * (4,1), (2,2) * (2,2)


In [1]:
import numpy as np

In [2]:
def matric_multi(A,B):
    m = len(A)          # จำนวนแถว A
    a = len(A[0])     # จำนวนหลัก A
    b = len(B)        # จำนวนแถว B
    n = len(B[0])       # จำนวนหลัก B
    C = np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            for sum in range(a):
                C[i,j] = C[i,j] + A[i,sum] * B[sum,j]
    return C

In [3]:
A = np.array([[14, 12, 13],[18, 15, 13]]) # ตัวอย่างชุดตัวเลข
B = np.array([[17, 19],[14, 12],[16, 17]])
matric_multi(A, B)

array([[614., 631.],
       [724., 743.]])

In [4]:
A = np.array([[4, 5, 7, 14],[12, 3, 14, 9],[3, 6, 11, 17],[11, 8, 5, 16]]) # ตัวอย่างชุดตัวเลข
B = np.array([[2],[4],[6],[8]])
matric_multi(A, B)

array([[182.],
       [192.],
       [232.],
       [212.]])

In [5]:
A = np.array([[4, 16],[11, 24]]) # ตัวอย่างชุดตัวเลข
B = np.array([[7, 8],[9, 47]])
matric_multi(A, B)

array([[ 172.,  784.],
       [ 293., 1216.]])